services:
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '22181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-1:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper-1
    ports:
      - '29092:29092'
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-1:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      # KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:29092
      KAFKA_CFG_LISTENERS: CLIENT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka-1:9092,EXTERNAL://host.docker.internal:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT

  notification-service:
    build: .
    depends_on:
      - kafka-1
    ports:
      - '2008:2008'
    environment:
      KAFKA_BROKERS: kafka-1:9092 
   